#!/bin/bash

sudo su 

cd 

sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

sudo yum upgrade

# Add required dependencies for the jenkins package

sudo yum install -y java 

sudo yum install -y jenkins

sudo systemctl start jenkins.service

sudo systemctl enable jenkins.service 
